name: 'publish @yesiree/outside'
run-name: publish @yesiree/outside — ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.actor }})

on:
  pull_request:
    branches: ['release']
    paths: ['projects/outside/**']
  push:
    branches: ['release']
    paths: ['projects/outside/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - working-directory: projects/outside
        run: deno install
      - working-directory: projects/outside
        run: deno lint
      - working-directory: projects/outside
        run: deno test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - working-directory: projects/outside
        run: deno publish
