name: 'publish @yesiree/outside'
run-name: publish @yesiree/outside — ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.actor }})

on:
  pull_request:
    branches: ['release']
    paths:
      - projects/outside/**
      - .github/workflows/npm-publish-outside.yml
  push:
    branches: ['release']
    paths:
      - projects/outside/**
      - .github/workflows/npm-publish-outside.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - working-directory: projects/outside
        run: npm ci
      - working-directory: projects/outside
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - working-directory: projects/outside
        run: npm ci
      - working-directory: projects/outside
        run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GHA_TOKEN }}
